#!/usr/bin/env bash
#
# Self-check for scripts/release.sh. It runs your script against a fake `make`
# so nothing is really built. Do not edit this file.
#
# Usage: ./scripts/check-release.sh

set -uo pipefail

SCRIPT="$(cd "$(dirname "$0")" && pwd)/release.sh"
PASS=0
FAIL=0

check() {
    local description="$1"; shift
    if "$@"; then
        echo "  PASS  $description"
        PASS=$((PASS + 1))
    else
        echo "  FAIL  $description"
        FAIL=$((FAIL + 1))
    fi
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# A fake project directory with a fake `make` that records what it was asked to do.
mkdir -p "$WORK/bin" "$WORK/project/scripts"
cp "$SCRIPT" "$WORK/project/scripts/release.sh"
cat > "$WORK/bin/make" <<'STUB'
#!/usr/bin/env bash
echo "$1" >> "$MAKE_LOG"
if [ "$1" = "test" ] && [ "${FAIL_TEST:-0}" = "1" ]; then
    exit 1
fi
if [ "$1" = "package" ]; then
    mkdir -p target
    echo "fake jar" > target/swiftparcel-jar-with-dependencies.jar
fi
exit 0
STUB
chmod +x "$WORK/bin/make"

run_release() {
    ( cd "$WORK/project" && rm -rf dist target && : > "$MAKE_LOG" \
      && PATH="$WORK/bin:$PATH" bash scripts/release.sh "$@" )
}

export MAKE_LOG="$WORK/make.log"

echo "Checking $SCRIPT"

# 1. No argument
run_release >"$WORK/out" 2>"$WORK/err"; code=$?
check "no argument: exits with status 2" test "$code" -eq 2
check "no argument: prints usage to stderr" grep -q "Usage" "$WORK/err"
check "no argument: builds nothing" test ! -s "$MAKE_LOG"

# 2. Invalid versions
for bad in "1.2" "v1.2.3" "1.2.x" "1.2.3.4" "abc"; do
    run_release "$bad" >"$WORK/out" 2>"$WORK/err"; code=$?
    check "invalid version '$bad': exits with status 1" test "$code" -eq 1
    check "invalid version '$bad': message on stderr" grep -q "Invalid version" "$WORK/err"
done
check "invalid version: builds nothing" test ! -s "$MAKE_LOG"

# 3. Valid version
run_release 2.3.1 >"$WORK/out" 2>"$WORK/err"; code=$?
check "valid version: exits with status 0" test "$code" -eq 0
check "valid version: runs make test then make package" \
    test "$(tr '\n' ' ' < "$MAKE_LOG")" = "test package "
check "valid version: jar copied to dist/swiftparcel-2.3.1.jar" \
    test -f "$WORK/project/dist/swiftparcel-2.3.1.jar"
check "valid version: prints the ready message" \
    grep -q "Release 2.3.1 ready in dist/" "$WORK/out"

# 4. Failing tests must stop the release
FAIL_TEST=1 run_release 2.3.1 >"$WORK/out" 2>"$WORK/err"; code=$?
check "failing tests: exits non-zero" test "$code" -ne 0
check "failing tests: make package is never run" \
    bash -c "! grep -q package '$MAKE_LOG'"
check "failing tests: no jar is published" \
    test ! -e "$WORK/project/dist/swiftparcel-2.3.1.jar"

echo
echo "Passed: $PASS   Failed: $FAIL"
[ "$FAIL" -eq 0 ]
